# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: testaus
author: JT
execute:
  execute_notebooks: cache

 
repository:
  url: https://github.com/jteeriaho/testi3  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

 
html:
  use_issues_button: false
  use_repository_button: true
  
launch_buttons:
  binderhub_url: "https://mybinder.org"
  thebe: true
  

